# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseSample

  target 'FirebaseSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseSampleUITests' do
    # Pods for testing
  end

 pod 'Firebase/Core'
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
 pod 'Firebase/Database'
 pod 'Firebase/Storage'

end
